Console.WriteLine("Ввод координат:");
Console.Write(" х:a - ");
double xa = double.Parse(Console.ReadLine() ?? "0");
Console.Write(" y:a - ");
double ya = double.Parse(Console.ReadLine() ?? "0");
Console.Write(" z:a - ");
double za = double.Parse(Console.ReadLine() ?? "0");
Console.Write(" x:b - ");
double xb = double.Parse(Console.ReadLine() ?? "0");
Console.Write(" y:b - ");
double yb = double.Parse(Console.ReadLine() ?? "0");
Console.Write(" z:b - ");
double zb = double.Parse(Console.ReadLine() ?? "0");
double a = xa-xb;
double b = ya-yb;
double c = za-zb;
double d = a*a+b*b;
double f = a*a+b*b+c*c;
double result2d = Math.Sqrt(d);
double result3d = Math.Sqrt(f);
Console.WriteLine("Расстояние между точками в пространстве 2D:  " + result2d);
Console.Write("Расстояние между точками в пространстве 3D:  " + result3d);
